version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python /code/composeexample/manage.py runserver 0.0.0.0:8000
    volumes:
      - /mnt/docker/django:/code
    ports:
      - "7800:8000"
    depends_on:
      - db
